name: Auto-Kanban Workflow

on:
  issues:
    types: [assigned, reopened, closed]
  pull_request:
    types: [opened, review_requested, merged]

jobs:
  kanban_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq (for JSON processing)
        run: sudo apt-get install jq

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Project ID
        id: get_project
        run: echo "PROJECT_ID=$(gh project list --owner ${{ github.repository_owner }} --format json | jq -r '.[] | select(.title==\"HoneyHole MVP Roadmap\") | .id')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "In Progress" when assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        run: gh project item-edit --id "${{ github.event.issue.node_id }}" --project-id "$PROJECT_ID" --field "Status=In Progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Review" when PR is created
        if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
        run: gh project item-edit --id "${{ github.event.pull_request.node_id }}" --project-id "$PROJECT_ID" --field "Status=Review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move issue to "Done" when PR is merged
        if: github.event.pull_request.merged == true
        run: gh project item-edit --id "${{ github.event.pull_request.node_id }}" --project-id "$PROJECT_ID" --field "Status=Done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
