name: Automate Kanban Board

on:
  issues:
    types: [labeled, unlabeled, opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  move-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Move issues based on labels
      uses: actions/github-script@v6
      with:
        script: |
          const columnName = {
            'todo': 'To do',
            'in-progress': 'In progress',
            'done': 'Done'
          }[context.payload.label.name.toLowerCase()];

          if (columnName) {
            const columns = await github.projects.listColumns({
              project_id: https://github.com/users/BryanZin123/projects/7 // Replace with your project ID
            });

            const column = columns.data.find(col => col.name === columnName);

            if (column) {
              await github.projects.moveProjectCard({
                card_id: context.payload.issue.node_id,
                column_id: column.id,
                position: 'top'
              });
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
